package piedel.piotr.thesis.configuration

const val TYPE_AUDIO = "application/vnd.google-apps.audio"
const val TYPE_GOOGLE_DOCS = "application/vnd.google-apps.document"
const val TYPE_GOOGLE_DRAWING = "application/vnd.google-apps.drawing"
const val TYPE_GOOGLE_DRIVE_FILE = "application/vnd.google-apps.file"
const val TYPE_GOOGLE_FORMS = "application/vnd.google-apps.form"
const val TYPE_GOOGLE_FUSION_TABLES = "application/vnd.google-apps.fusiontable"
const val TYPE_GOOGLE_MY_MAPS = "application/vnd.google-apps.map"
const val TYPE_PHOTO = "application/vnd.google-apps.photo"
const val TYPE_GOOGLE_SLIDES = "application/vnd.google-apps.presentation"
const val TYPE_GOOGLE_APPS_SCRIPTS = "application/vnd.google-apps.script"
const val TYPE_GOOGLE_SITES = "application/vnd.google-apps.site"
const val TYPE_GOOGLE_SHEETS = "application/vnd.google-apps.spreadsheet"
const val TYPE_UNKNOWN = "application/vnd.google-apps.unknown"
const val TYPE_VIDEO = "application/vnd.google-apps.video"
const val TYPE_3_RD_PARTY_SHORTCUT = "application/vnd.google-apps.drive-sdk"
const val TYPE_IMAGE_FILE = "image/jpeg"
const val TYPE_TEXT_PLAIN = "text/plain"